'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const js = fs.readFileSync(path.join(root, 'app.js'), 'utf8');
const gas = fs.readFileSync(path.join(root, 'google-apps-script/Code.gs'), 'utf8');

assert.match(html, /NEW2AN 2026/);
assert.match(html, /15–17 December 2026/);
assert.match(html, /No student rate or discount is offered/);
assert.match(html, /Download proforma PDF/);
assert.match(html, /Upload proof of payment/);
assert.match(html, /Excursion planning/);
assert.match(html, /USD 50 per participant/);
assert.match(html, /href="#admin"/);
assert.match(html, /Seeing Through AI: Deep Learning for Computer Vision/);
assert.match(html, /21 July 2026/);
assert.match(html, /new2an@crisglobal\.org/);
assert.doesNotMatch(html, /SICET|Excellence Award|SLIIT payment portal/i);
assert.match(js, /earlyFee:\s*400/);
assert.match(js, /lateFee:\s*500/);
assert.match(js, /excursionFeeUsd:\s*50/);
assert.match(js, /earlyDeadline:\s*'2026-10-31/);
assert.match(js, /apiUrl:\s*'https:\/\/script\.google\.com\/macros\/s\/AKfycbxW-RbC28FXkOlnrwYU2s4UE-YI7UsauUqTUUKoGunyZgdHGAwgyYug6NIkhEPnqS0J\/exec'/);
assert.match(js, /function generateProforma/);
assert.match(js, /EXCURSION - PAY ON THE EXCURSION DAY/);
assert.match(js, /savePublicSettings/);
assert.match(js, /1 USD = EUR/);
assert.match(js, /PROFORMA NUMBER/);
assert.match(js, /Issued by/);
assert.match(js, /Billing_Legal_Name/);
assert.match(js, /function updateBillingVisibility/);
assert.match(js, /Page 1 of 1/);
assert.match(js, /not proof of payment, a tax invoice, or a receipt/);
assert.match(js, /paymentProofFiles/);
assert.match(js, /Travel Logistics/);
assert.match(js, /Accommodation/);
assert.match(js, /Name for badge and certificate/);
assert.match(js, /Changes from the CMT submission/);
assert.match(js, /Help request category/);
assert.match(js, /Support Requests/);
assert.match(js, /Certificates/);
assert.match(js, /function renderWorkshopAdmin/);
assert.doesNotMatch(js, /Sampath Bank|SICET/i);
assert.match(gas, /Script Properties:[\s\S]*MAIN_FOLDER_ID/);
assert.match(gas, /NEW2AN 2026 - Master Registration Database/);
assert.match(gas, /NEW2AN 2026 - Registration Administration/);
assert.match(gas, /02 - Payment Proofs/);
assert.match(gas, /DriveApp\.createFolder\(MAIN_FOLDER_NAME\)/);
assert.match(gas, /Paper_Count/);
assert.match(gas, /Travel_Agency_Assistance/);
assert.match(gas, /Accommodation_Assistance/);
assert.match(gas, /Certificate_Name/);
assert.match(gas, /CMT_Changes/);
assert.match(gas, /Support_Request/);
assert.match(gas, /Payment_Proof_Base64/);
assert.match(gas, /Excursion_Participant_Count/);
assert.match(gas, /EXCURSION_FEE_USD = 50/);
assert.match(gas, /USD_TO_EUR_RATE/);
assert.match(gas, /Excursion_Total_EUR_Indicative/);
assert.match(gas, /function savePublicSettings/);
assert.match(gas, /INVOICE_ISSUER_LEGAL_NAME/);
assert.match(gas, /INVOICE_PAYMENT_INSTRUCTIONS/);
assert.match(gas, /required for an institutional invoice/);
assert.match(gas, /function headerMap/);
assert.match(gas, /function writeSheetRecord/);
assert.doesNotMatch(gas, /header order is incompatible/);
assert.match(gas, /Future_Workshop_Updates/);
assert.match(gas, /function saveWorkshops/);
assert.match(gas, /WORKSHOPS_JSON/);
assert.match(gas, /PROOF_SUBMITTED/);
assert.doesNotMatch(gas, /1REXNut|SICET/i);
console.log('NEW2AN contract checks passed.');
