'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const js = fs.readFileSync(path.join(root, 'app.js'), 'utf8');
const gas = fs.readFileSync(path.join(root, 'google-apps-script/Code.gs'), 'utf8');

assert.match(html, /NEW2AN 2026/);
assert.match(html, /15–17 December 2026/);
assert.match(html, /No student rate or discount is offered/);
assert.match(html, /Download proforma PDF/);
assert.match(html, /Upload proof of payment/);
assert.match(html, /Excursion planning/);
assert.match(html, /Seeing Through AI: Deep Learning for Computer Vision/);
assert.match(html, /21 July 2026/);
assert.match(html, /new2an@crisglobal\.org/);
assert.doesNotMatch(html, /SICET|Excellence Award|SLIIT payment portal/i);
assert.match(js, /earlyFee:\s*400/);
assert.match(js, /lateFee:\s*500/);
assert.match(js, /earlyDeadline:\s*'2026-10-31/);
assert.match(js, /apiUrl:\s*''/);
assert.match(js, /function generateProforma/);
assert.match(js, /paymentProofFiles/);
assert.match(js, /Travel Logistics/);
assert.match(js, /Accommodation/);
assert.match(js, /Name for badge and certificate/);
assert.match(js, /Changes from the CMT submission/);
assert.match(js, /Help request category/);
assert.match(js, /Support Requests/);
assert.match(js, /Certificates/);
assert.match(js, /function renderWorkshopAdmin/);
assert.doesNotMatch(js, /AKfy|Sampath Bank|SICET/i);
assert.match(gas, /Script Properties:[\s\S]*MAIN_FOLDER_ID/);
assert.match(gas, /NEW2AN 2026 - Master Registration Database/);
assert.match(gas, /NEW2AN 2026 - Registration Administration/);
assert.match(gas, /02 - Payment Proofs/);
assert.match(gas, /DriveApp\.createFolder\(MAIN_FOLDER_NAME\)/);
assert.match(gas, /Paper_Count/);
assert.match(gas, /Travel_Agency_Assistance/);
assert.match(gas, /Accommodation_Assistance/);
assert.match(gas, /Certificate_Name/);
assert.match(gas, /CMT_Changes/);
assert.match(gas, /Support_Request/);
assert.match(gas, /Payment_Proof_Base64/);
assert.match(gas, /Excursion_Participant_Count/);
assert.match(gas, /Future_Workshop_Updates/);
assert.match(gas, /function saveWorkshops/);
assert.match(gas, /WORKSHOPS_JSON/);
assert.match(gas, /PROOF_SUBMITTED/);
assert.doesNotMatch(gas, /1REXNut|SICET/i);
console.log('NEW2AN contract checks passed.');
