'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const js = fs.readFileSync(path.join(root, 'app.js'), 'utf8');
const gas = fs.readFileSync(path.join(root, 'google-apps-script/Code.gs'), 'utf8');
const travelHtml = fs.readFileSync(path.join(root, 'excursion.html'), 'utf8');
const travelJs = fs.readFileSync(path.join(root, 'excursion.js'), 'utf8');

assert.match(html, /NEW2AN 2026/);
assert.match(html, /15–17 December 2026/);
assert.match(html, /No student rate or discount is offered/);
assert.match(html, /Download proforma PDF/);
assert.match(html, /Upload proof of registration payment/);
assert.match(html, /Excursion planning/);
assert.match(html, /Approximately USD 50 per participant/);
assert.match(html, /Includes transport and evening refreshment\. Lunch is not included\./);
assert.match(html, /Non-author attendee/);
assert.match(html, /Industry professional/);
assert.match(html, /Vegetarian/);
assert.match(html, /Non-vegetarian/);
assert.match(html, /Halal/);
assert.doesNotMatch(html, /Invited or keynote speaker|Committee member \/ chair|Non-author academic \/ researcher|Vegan|Gluten-free/);
assert.match(html, /href="#admin"/);
assert.match(html, /AI-Based Communications Towards 6G/);
assert.match(html, /11 September 2026/);
assert.match(html, /Registration_Category/);
assert.match(html, /Gala dinner ticket/);
assert.match(html, /3MT Competition/);
assert.match(html, /USD 30/);
assert.match(html, /Global Undergraduate Hackathon/);
assert.match(html, /payhere\.lk\/pay\/o89eb0a8e/);
assert.match(html, /new2an@crisglobal\.org/);
assert.doesNotMatch(html, /SICET|SLIIT payment portal/i);
assert.match(js, /earlyFee:\s*400/);
assert.match(js, /lateFee:\s*500/);
assert.match(js, /sriLankanEarlyFee:\s*40000/);
assert.match(js, /sriLankanLateFee:\s*50000/);
assert.match(js, /excursionFeeUsd:\s*50/);
assert.match(js, /earlyDeadline:\s*'2026-10-31/);
assert.match(js, /apiUrl:\s*'https:\/\/script\.google\.com\/macros\/s\/AKfycbxW-RbC28FXkOlnrwYU2s4UE-YI7UsauUqTUUKoGunyZgdHGAwgyYug6NIkhEPnqS0J\/exec'/);
assert.match(js, /function generateProforma/);
assert.match(js, /function currentRegistrationPrice/);
assert.match(js, /LK_AUTHOR/);
assert.match(js, /ESTIMATED EXCURSION COST - PAY ON THE EXCURSION DAY/);
assert.match(js, /saved\.pricing/);
assert.match(js, /authoritative invoice pricing/);
assert.match(js, /invoiceSettingsApproved/);
assert.match(js, /organiser has not yet verified and approved/);
assert.match(js, /savePublicSettings/);
assert.match(js, /1 USD = EUR/);
assert.match(js, /PROFORMA NUMBER/);
assert.match(js, /Issued by/);
assert.match(js, /Billing_Legal_Name/);
assert.match(js, /function updateBillingVisibility/);
assert.match(js, /Page 1 of 1/);
assert.match(js, /not proof of payment, a tax invoice, or a receipt/);
assert.match(js, /paymentProofFiles/);
assert.match(js, /Travel Logistics/);
assert.match(js, /Accommodation/);
assert.match(js, /Name for badge and certificate/);
assert.match(js, /Changes from the CMT submission/);
assert.match(js, /Help request category/);
assert.match(js, /Support Requests/);
assert.match(js, /Certificates/);
assert.match(js, /function renderWorkshopAdmin/);
assert.doesNotMatch(js, /Sampath Bank|SICET/i);
assert.match(gas, /Script Properties:[\s\S]*MAIN_FOLDER_ID/);
assert.match(gas, /NEW2AN 2026 - Master Registration Database/);
assert.match(gas, /NEW2AN 2026 - Registration Administration/);
assert.match(gas, /function getRegistrationFolder/);
assert.match(gas, /function saveInvoiceVersion/);
assert.match(gas, /INVOICES_FOLDER = 'Invoices'/);
assert.match(gas, /PAYMENT_PROOFS_FOLDER = 'Payment Proofs'/);
assert.match(gas, /registration\.json/);
assert.doesNotMatch(gas, /oldFiles\.forEach/);
assert.match(js, /action:'saveInvoiceVersion'/);
assert.match(js, /doc\.output\('datauristring'\)/);
assert.match(js, /let editToken = ''/);
assert.doesNotMatch(js, /function makeReferenceId/);
assert.match(gas, /function issueEditToken/);
assert.match(gas, /function verifyEditToken/);
assert.match(gas, /verifyEditToken\(editToken,data\.Reference_ID,data\.Email\)/);
assert.match(gas, /verifyEditToken\(body\.editToken,referenceId,email\)/);
assert.match(gas, /PROOF_SUBMITTED_AMOUNT_MISMATCH/);
assert.match(gas, /function registrationPriceFor/);
assert.match(gas, /SRI_LANKAN_AUTHOR_LATE_25_PERCENT_SURCHARGE/);
assert.match(gas, /Registration_Category/);
assert.match(gas, /Gala_Dinner_Fee/);
assert.match(gas, /const SCHEMA_VERSION = 4/);
assert.match(gas, /Non-author attendee/);
assert.match(gas, /dietaryPreferences:DIETARY_PREFERENCES/);
assert.match(gas, /pricing:\{/);
assert.doesNotMatch(gas, /3MT/);
assert.match(gas, /invoice-archive:/);
assert.match(gas, /archiveCount>=20/);
assert.match(gas, /DriveApp\.createFolder\(MAIN_FOLDER_NAME\)/);
assert.match(gas, /Paper_Count/);
assert.match(gas, /Travel_Agency_Assistance/);
assert.match(gas, /Accommodation_Assistance/);
assert.match(gas, /Certificate_Name/);
assert.match(gas, /CMT_Changes/);
assert.match(gas, /Support_Request/);
assert.match(gas, /Payment_Proof_Base64/);
assert.match(gas, /Excursion_Participant_Count/);
assert.match(gas, /EXCURSION_FEE_USD = 50/);
assert.match(gas, /USD_TO_EUR_RATE/);
assert.match(gas, /Excursion_Total_EUR_Indicative/);
assert.match(gas, /function savePublicSettings/);
assert.match(gas, /INVOICE_ISSUER_LEGAL_NAME/);
assert.match(gas, /INVOICE_PAYMENT_INSTRUCTIONS/);
assert.match(gas, /INVOICE_SETTINGS_APPROVED/);
assert.match(gas, /invoiceSettingsApproved:approved/);
assert.match(gas, /usdToEurRate:approved&&stored>0\?stored:0/);
assert.match(gas, /Invoice archiving is disabled until the organiser verifies/);
assert.match(gas, /required for an institutional invoice/);
assert.match(gas, /function headerMap/);
assert.match(gas, /function writeSheetRecord/);
assert.doesNotMatch(gas, /header order is incompatible/);
assert.match(gas, /Future_Workshop_Updates/);
assert.match(gas, /function saveWorkshops/);
assert.match(gas, /WORKSHOPS_JSON/);
assert.match(gas, /PROOF_SUBMITTED/);
assert.doesNotMatch(gas, /1REXNut|SICET/i);
assert.match(html, /href="excursion\.html"/);
assert.match(travelHtml, /Travel &amp; excursion details/);
assert.match(travelHtml, /Flight &amp; passport requirements/);
assert.match(travelHtml, /Passport date of expiry/);
assert.match(travelHtml, /approved travel service provider/);
assert.match(travelJs, /action:'submitTravelDetails'/);
assert.match(travelJs, /Excursion_Interest!=='Yes'/);
assert.match(travelJs, /Travel_Agency_Assistance==='Yes — flight options'/);
assert.doesNotMatch(travelHtml, /name="(?:Full_Name|Phone|Organization|Country_of_Residence|Nationality|Travel_Profession|Air_Ticket_Assistance)"/);
assert.match(gas, /TRAVEL_DOCUMENTS_FOLDER = 'Travel Documents'/);
assert.match(gas, /function saveTravelDetails/);
assert.match(gas, /function validateTravelDetails/);
assert.match(gas, /Passport_Bio_Page_Files/);
console.log('NEW2AN contract checks passed.');
